{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "chart.selectorLabels" (dict "name" $name "root" $) | nindent 4 }}
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  selector:
    {{- include "chart.selectorLabels" (dict "name" $name "root" $) | nindent 4 }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: http
      {{- if $svc.h2c }}
      appProtocol: kubernetes.io/h2c
      {{- end }}
    {{- range $svc.extraPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .name }}
    {{- end }}
{{- end }}
