version: 2
updates:
  - package-ecosystem: gomod
    directory: /api/common
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        patterns: ["*"]
