services:
  expendit-frontend:
    build:
      context: ./web
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
    restart: always
    depends_on:
      - expendit-backend
    networks:
      - next-envoy
  
  expendit-home:
    build:
      context: ./Home
      target: development
    ports:
      - 5000:5000
    volumes:
      - ./Home:/app
    restart: always

  expendit-backend:
    build: ./api/common
    ports:
      - "9000:9000"
    env_file:
      - ./api/common/.env 

networks:
  next-envoy:
  envoy-go:
  go-db: