/**
 * @fileoverview gRPC-Web generated client stub for pb
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.25.0-rc2
// source: proto/user.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_user_pb from '../proto/user_pb';


export class UserServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetUser = new grpcWeb.MethodDescriptor(
    '/pb.UserService/GetUser',
    grpcWeb.MethodType.UNARY,
    proto_user_pb.GetUserRequest,
    proto_user_pb.GetUserResponse,
    (request: proto_user_pb.GetUserRequest) => {
      return request.serializeBinary();
    },
    proto_user_pb.GetUserResponse.deserializeBinary
  );

  getUser(
    request: proto_user_pb.GetUserRequest,
    metadata: grpcWeb.Metadata | null): Promise<proto_user_pb.GetUserResponse>;

  getUser(
    request: proto_user_pb.GetUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_user_pb.GetUserResponse) => void): grpcWeb.ClientReadableStream<proto_user_pb.GetUserResponse>;

  getUser(
    request: proto_user_pb.GetUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_user_pb.GetUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.UserService/GetUser',
        request,
        metadata || {},
        this.methodDescriptorGetUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.UserService/GetUser',
    request,
    metadata || {},
    this.methodDescriptorGetUser);
  }

  methodDescriptorCreateUser = new grpcWeb.MethodDescriptor(
    '/pb.UserService/CreateUser',
    grpcWeb.MethodType.UNARY,
    proto_user_pb.CreateUserRequest,
    proto_user_pb.CreateUserResponse,
    (request: proto_user_pb.CreateUserRequest) => {
      return request.serializeBinary();
    },
    proto_user_pb.CreateUserResponse.deserializeBinary
  );

  createUser(
    request: proto_user_pb.CreateUserRequest,
    metadata: grpcWeb.Metadata | null): Promise<proto_user_pb.CreateUserResponse>;

  createUser(
    request: proto_user_pb.CreateUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_user_pb.CreateUserResponse) => void): grpcWeb.ClientReadableStream<proto_user_pb.CreateUserResponse>;

  createUser(
    request: proto_user_pb.CreateUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_user_pb.CreateUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.UserService/CreateUser',
        request,
        metadata || {},
        this.methodDescriptorCreateUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.UserService/CreateUser',
    request,
    metadata || {},
    this.methodDescriptorCreateUser);
  }

  methodDescriptorUpdateUser = new grpcWeb.MethodDescriptor(
    '/pb.UserService/UpdateUser',
    grpcWeb.MethodType.UNARY,
    proto_user_pb.UpdateUserRequest,
    proto_user_pb.UpdateUserResponse,
    (request: proto_user_pb.UpdateUserRequest) => {
      return request.serializeBinary();
    },
    proto_user_pb.UpdateUserResponse.deserializeBinary
  );

  updateUser(
    request: proto_user_pb.UpdateUserRequest,
    metadata: grpcWeb.Metadata | null): Promise<proto_user_pb.UpdateUserResponse>;

  updateUser(
    request: proto_user_pb.UpdateUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_user_pb.UpdateUserResponse) => void): grpcWeb.ClientReadableStream<proto_user_pb.UpdateUserResponse>;

  updateUser(
    request: proto_user_pb.UpdateUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_user_pb.UpdateUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.UserService/UpdateUser',
        request,
        metadata || {},
        this.methodDescriptorUpdateUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.UserService/UpdateUser',
    request,
    metadata || {},
    this.methodDescriptorUpdateUser);
  }

  methodDescriptorDeleteUser = new grpcWeb.MethodDescriptor(
    '/pb.UserService/DeleteUser',
    grpcWeb.MethodType.UNARY,
    proto_user_pb.DeleteUserRequest,
    proto_user_pb.DeleteUserResponse,
    (request: proto_user_pb.DeleteUserRequest) => {
      return request.serializeBinary();
    },
    proto_user_pb.DeleteUserResponse.deserializeBinary
  );

  deleteUser(
    request: proto_user_pb.DeleteUserRequest,
    metadata: grpcWeb.Metadata | null): Promise<proto_user_pb.DeleteUserResponse>;

  deleteUser(
    request: proto_user_pb.DeleteUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_user_pb.DeleteUserResponse) => void): grpcWeb.ClientReadableStream<proto_user_pb.DeleteUserResponse>;

  deleteUser(
    request: proto_user_pb.DeleteUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_user_pb.DeleteUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.UserService/DeleteUser',
        request,
        metadata || {},
        this.methodDescriptorDeleteUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.UserService/DeleteUser',
    request,
    metadata || {},
    this.methodDescriptorDeleteUser);
  }

  methodDescriptorGetAllUsers = new grpcWeb.MethodDescriptor(
    '/pb.UserService/GetAllUsers',
    grpcWeb.MethodType.UNARY,
    proto_user_pb.Empty,
    proto_user_pb.GetAllUsersResponse,
    (request: proto_user_pb.Empty) => {
      return request.serializeBinary();
    },
    proto_user_pb.GetAllUsersResponse.deserializeBinary
  );

  getAllUsers(
    request: proto_user_pb.Empty,
    metadata: grpcWeb.Metadata | null): Promise<proto_user_pb.GetAllUsersResponse>;

  getAllUsers(
    request: proto_user_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_user_pb.GetAllUsersResponse) => void): grpcWeb.ClientReadableStream<proto_user_pb.GetAllUsersResponse>;

  getAllUsers(
    request: proto_user_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_user_pb.GetAllUsersResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.UserService/GetAllUsers',
        request,
        metadata || {},
        this.methodDescriptorGetAllUsers,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.UserService/GetAllUsers',
    request,
    metadata || {},
    this.methodDescriptorGetAllUsers);
  }

}

