import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import { expect, test } from "@playwright/test";

/**
 * SEO plumbing lock (fleet, 2026-07-21): sitemap + robots + canonical +
 * og/twitter card + product-branded icons.
 *
 * This spec is BYTE-IDENTICAL across apparule/expendit/upstat (tooling
 * canon) — per-product expectations live in the config below keyed by
 * `package.json` name, the scripts/check-boundaries.mjs pattern.
 *
 * The favicon table pins each product's OWN mark bytes and proves no two
 * products ship the same icon (apparule and upstat both shipped the stock
 * create-next-app icon until 2026-07-21). Assets are generated by
 * scripts/generate-brand-assets.mjs — regenerating means updating all
 * three rows in all three repos in the same pass.
 */

interface SeoProfile {
  /** Canonical production origin (no trailing slash). */
  base: string;
  /** Public routes the sitemap must enumerate ("/" = the origin itself). */
  sitemapRoutes: string[];
  /** sha256 of the committed src/app/favicon.ico, served at /favicon.ico. */
  faviconSha256: string;
}

const PRODUCTS: Record<string, SeoProfile> = {
  apparule: {
    base: "https://apparule.cuesoft.io",
    sitemapRoutes: ["/", "/docs/api"],
    faviconSha256:
      "d905511df70290da933430d8153127eb4a4e7e981495dfc9542891c202c4d2e0",
  },
  expendit: {
    base: "https://expendit.cuesoft.io",
    sitemapRoutes: ["/", "/docs/api"],
    faviconSha256:
      "5e362756b324e43dec5efd516687f5432c1b5be1b2273529e39db65ee152af82",
  },
  upstat: {
    base: "https://upstat.cuesoft.io",
    sitemapRoutes: ["/", "/docs/api", "/status/upstat"],
    faviconSha256:
      "d6c2c8bb146708db10bd09f2d987b3884433e71a1fb992d87e509ad2766f1d2b",
  },
};

const pkgName: string = JSON.parse(
  readFileSync(path.join(__dirname, "..", "package.json"), "utf8"),
).name;
const product = PRODUCTS[pkgName];
const siblings = Object.entries(PRODUCTS).filter(([name]) => name !== pkgName);

const escapeRe = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

test("sitemap.xml returns 200 and enumerates exactly the public routes", async ({
  request,
}) => {
  const res = await request.get("/sitemap.xml");
  expect(res.status()).toBe(200);
  const body = await res.text();
  expect(body).toContain("<urlset");
  for (const route of product.sitemapRoutes) {
    const url = route === "/" ? product.base : `${product.base}${route}`;
    expect(body).toMatch(new RegExp(`<loc>${escapeRe(url)}/?</loc>`));
  }
  // NO dashboard/auth routes — the app shell is fenced off (crawl policy).
  expect(body).not.toContain("/dashboard");
  expect(body).not.toContain("/signin");
});

test("robots.txt allows the public surface, fences the app, references the sitemap", async ({
  request,
}) => {
  const res = await request.get("/robots.txt");
  expect(res.status()).toBe(200);
  const body = await res.text();
  expect(body).toMatch(/User-Agent: \*/i);
  expect(body).toMatch(/Allow: \//i);
  expect(body).toMatch(/Disallow: \/dashboard/i);
  expect(body).toMatch(/Disallow: \/api/i);
  expect(body).toContain(`Sitemap: ${product.base}/sitemap.xml`);
});

test("home carries its canonical and the og/twitter card contract", async ({
  page,
  request,
}) => {
  await page.goto("/");

  // Canonical: the page's own production URL (metadataBase + "./").
  const canonical = page.locator('link[rel="canonical"]');
  await expect(canonical).toHaveAttribute(
    "href",
    new RegExp(`^${escapeRe(product.base)}/?$`),
  );

  // og:image: the 1200×630 card, and the asset actually resolves.
  const ogImage = await page
    .locator('meta[property="og:image"]')
    .getAttribute("content");
  expect(ogImage).toBeTruthy();
  const ogUrl = new URL(ogImage!, product.base);
  expect(ogUrl.pathname).toMatch(/opengraph-image\.png$/);
  const ogRes = await request.get(ogUrl.pathname + ogUrl.search);
  expect(ogRes.status()).toBe(200);
  expect(ogRes.headers()["content-type"]).toContain("image/png");
  await expect(page.locator('meta[property="og:image:width"]')).toHaveAttribute(
    "content",
    "1200",
  );
  await expect(
    page.locator('meta[property="og:image:height"]'),
  ).toHaveAttribute("content", "630");

  // twitter: large-image card (falls back to og:image for the asset).
  await expect(page.locator('meta[name="twitter:card"]')).toHaveAttribute(
    "content",
    "summary_large_image",
  );
});

test("icons are product-branded and distinct from the sibling products", async ({
  page,
  request,
}) => {
  // The served favicon is this product's own mark…
  const res = await request.get("/favicon.ico");
  expect(res.status()).toBe(200);
  const sha = createHash("sha256")
    .update(await res.body())
    .digest("hex");
  expect(sha).toBe(product.faviconSha256);
  // …and never a sibling's bytes (the fleet's stock-icon regression class).
  for (const [name, sibling] of siblings) {
    expect(sha, `favicon must differ from ${name}'s`).not.toBe(
      sibling.faviconSha256,
    );
  }

  // apple-touch-icon: linked from the page and resolves.
  await page.goto("/");
  const apple = await page
    .locator('link[rel="apple-touch-icon"]')
    .getAttribute("href");
  expect(apple).toBeTruthy();
  const appleUrl = new URL(apple!, product.base);
  const appleRes = await request.get(appleUrl.pathname + appleUrl.search);
  expect(appleRes.status()).toBe(200);
  expect(appleRes.headers()["content-type"]).toContain("image/png");
});
